monogenic_disease_report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('report/', include('report.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.urls import path
from . import views

app_name = 'report'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('upload', views.model_form_upload, name='upload'),
    path('create', views.ReportCreate.as_view(), name='create'),
    path('statistics', views.Statistics.as_view(), name='statistics'),
    path('api/echarts/', views.echarts_data, name='api-echarts')
]

report/models.py
from django.db import models
from datetime import datetime

# Create your models here.
def upload_filename(instance, filename):
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    new_filename = "documents/{family}-{name}-{gene}-{upload}.pdf".format(
        family = instance.sample.family,
        name = instance.sample.name,
        gene = instance.pathogenicity.gene,
        upload = timestamp
    )
    print("OLD: " + filename)
    print("NEW: " + new_filename)
    return new_filename

class Pathogenicity(models.Model):
    disease = models.CharField(max_length = 200, blank=True, null=True)
    gene = models.CharField(max_length = 200, blank=True, null=True)
    variant = models.CharField(max_length = 200, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now = True, blank=True)
    class Meta:
        ordering = ['-id']
        unique_together = (
            ('disease', 'gene', 'variant')
        )

class Sample(models.Model):
    family = models.CharField(max_length = 200, blank=True, null=True)
    name = models.CharField(max_length = 200, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now = True, blank=True)
    class Meta:
        ordering = ['-id']
        unique_together = (
            ('family', 'name')
        )

class Report(models.Model):
    sample = models.ForeignKey(Sample, on_delete = models.CASCADE)
    pathogenicity = models.ForeignKey(Pathogenicity, on_delete = models.CASCADE)
    pdf = models.FileField(upload_to=upload_filename)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return join(" ",
                    (self.sample.name,
                     self.pathogenicity.disease,
                     self.pathogenicity.gene)
                    )

report/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from .models import Pathogenicity, Sample, Report

class SampleForm(forms.ModelForm):
    class Meta:
        model = Sample
        fields = ('family', 'name')
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

class PathogenicityForm(forms.ModelForm):
    class Meta:
        model = Pathogenicity
        fields = ('disease', 'gene', 'variant')
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('sample', 'pathogenicity', 'pdf')

report/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView
from django.db.models import Count

from .models import Sample, Pathogenicity, Report
from .forms import ReportForm

# Create your views here.
class IndexView(ListView):
    paginate_by = 30
    model = Report
    template_name = 'report/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # keep search condition
        context['family']  = self.request.GET.get('family', '')
        context['name']    = self.request.GET.get('name', '')
        context['disease'] = self.request.GET.get('disease', '')
        context['gene']    = self.request.GET.get('gene', '')
        context['variant'] = self.request.GET.get('variant', '')
        
        context['search'] = self.request.GET.urlencode()
        if context['search'] != '':
            context['search'] += '&'
        return context

    def get_queryset(self):
        reports = Report.objects.all()
        if 'family' in self.request.GET:
            reports = reports.filter(sample__family__icontains = self.request.GET['family'])
        if 'name' in self.request.GET:
            reports = reports.filter(sample__name__icontains = self.request.GET['name'])
        if 'disease' in self.request.GET:
            reports = reports.filter(pathogenicity__disease__icontains = self.request.GET['disease'])
        if 'gene' in self.request.GET:
            reports = reports.filter(pathogenicity__gene__icontains = self.request.GET['gene'])
        if 'variant' in self.request.GET:
            reports = reports.filter(pathogenicity__variant__icontains = self.request.GET['variant'])
        return reports

def model_form_upload(request):
    msg = ''
    if request.method == 'POST' and request.POST.get('check_value', 0) == '1':
        print(request.POST)
        #check family and sample name exists
        try:
            sample_obj = Sample.objects.get(
                family = request.POST['family'],
                name = request.POST['name']
            )
        except ObjectDoesNotExist:
            sample_obj = Sample(
                id = Sample.objects.order_by('-id')[0].id + 1,
                family = request.POST['family'],
                name = request.POST['name']
            )
            sample_obj.save()

        #check pathogenicity exists
        try:
            pathogenicity_obj = Pathogenicity.objects.get(
                disease = request.POST['disease'],
                gene = request.POST['gene'],
                variant = request.POST['variant']
            )
        except ObjectDoesNotExist:
            pathogenicity_obj = Pathogenicity(
                id = Pathogenicity.objects.order_by('-id')[0].id + 1,
                disease = request.POST['disease'],
                gene = request.POST['gene'],
                variant = request.POST['variant']
            )
            pathogenicity_obj.save()

        # upload pdf and link to sample and pathogenicity
        report_obj = Report(
            id = Report.objects.order_by('-id')[0].id + 1,
            pdf = request.FILES['pdf'],
            pathogenicity = pathogenicity_obj,
            sample = sample_obj
        )
        try:
            report_obj.save()
            # messages.success(request, '报告上传成功！')
            msg = '报告上传成功！'
            # return HttpResponseRedirect(reverse('report:index'))
        except:
            # messages.error(request, '报告上传失败！')
            msg = '报告上传失败！'
        # return HttpResponseRedirect(reverse('report:upload'))

    report_form = ReportForm()
    return render(request, 'report/upload.html', {
        'form': report_form,
        'msg': msg
    })


class ReportCreate(CreateView):
    model = Report
    fields = ['sample', 'pathogenicity', 'pdf']
    template_name_suffix = '_create_form'

class Statistics(TemplateView):
    template_name = "report/statistics.html"

def echarts_data(request):
    report_data = Report.objects.all()
    years = [2015, 2016, 2017, 2018, 2019, 2020]
    counts = [ report_data.filter(sample__updated_at__year=y).count() for y in years]
    genes = report_data.values('pathogenicity__gene')\
        .annotate(gene_counts = Count('sample__family', distinct=True))\
        .order_by('-gene_counts')[0:10]
    diseases = report_data.filter(pathogenicity__disease__isnull=False)\
        .values('pathogenicity__disease')\
        .annotate(disease_counts = Count('sample__family', distinct=True))\
        .order_by('-disease_counts')[0:10]
    jsondata = {
        "years": years,
        "counts": counts,
        "top_10_genes": list(reversed([x['pathogenicity__gene'] for x in genes])),
        "top_10_gene_counts": list(reversed([x['gene_counts'] for x in genes])),
        "top_10_diseases": list(reversed([x['pathogenicity__disease'] for x in diseases])),
        "top_10_disease_counts": list(reversed([x['disease_counts'] for x in diseases])),
    }

    return JsonResponse(jsondata)

report/templates/report/index.html
{% extends "report/layout.html" %}
{% load static %}
<!-- head -->
{% block title %} 国妇婴单基因病报告数据库-首页{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'report/css/index.css' %}" >
{% endblock %}

{% block scripts %}
  <script src="{% static 'report/js/index.js' %}"></script>
{% endblock %}

<!-- body -->
{% block content %}
<div class="container">
  <div class="col-md-12 text-center" style="margin: 2em auto;">
    <h1>单基因病报告数据库</h1>
  </div>
    <!-- Search Form -->
    <form method="get" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="form-group inline col-md-3">
          <label for="family" class="col-md-3 col-form-label">家系号</label>
          <div class="col-md-8">
            <input type="text" class="form-control" name="family" value="{{ family }}">
          </div>
        </div>
        <div class="form-group inline col-md-3">
          <label for="name" class="col-md-3 col-form-label">姓&nbsp;&nbsp;&nbsp;名</label>
          <div class="col-md-8">
            <input type="text" class="form-control" name="name" value="{{ name }}">
          </div>
        </div>
        <div class="form-group inline col-md-3">
          <label for="disease" class="col-md-3 col-form-label">疾&nbsp;&nbsp;&nbsp;病</label>
          <div class="col-md-8">
            <input type="text" class="form-control" name="disease" value="{{ disease }}">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="form-group inline col-md-3">
          <label for="gene" class="col-md-3 col-form-label">基因</label>
          <div class="col-md-8">
            <input type="text" class="form-control" name="gene" value="{{ gene }}">
          </div>
        </div>
        <div class="form-group inline col-md-3">
          <label for="variant" class="col-md-3 col-form-label">致病变异</label>
          <div class="col-md-8">
            <input type="text" class="form-control" name="variant" value="{{ variant }}">
          </div>
        </div>
        <div class="form-group inline col-md-1">
          <button type="submit" class="btn btn-lg btn-primary"> 搜索 </button>
        </div>
        <div class="form-group inline col-md-2">
          <a href="{% url 'report:upload' %}" class="btn btn-lg btn-primary">新建</a>
        </div>
      </div>
    </form>

  <!-- Display Table -->
  <p>共找到{{ paginator.count }}条记录。</p>
  <div class="table-responsive">
    <table class="table table-striped table-hover table-fixed" id="data_table">
      <thead>
        <tr>
          <th scope="col" style="width: 12%">家系号</th>
          <th scope="col" style="width: 10%">样本名</th>
          <th scope="col" style="width: 15%">疾病名称</th>
          <th scope="col" style="width: 10%">基因</th>
          <th scope="col" style="width: 30%">致病位点</th>
          <th scope="col" style="width: 15%">上传时间</th>
          <th scope="col" style="width: 8%">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for report in page_obj %}
        <!-- <tr onclick="document.location = '/media/{{ report.pdf }}'; "> -->
          <tr data-path="/media/{{ report.pdf }}">
            <td>{{ report.sample.family }}</td>
            <td>{{ report.sample.name }}</td>
            <td>{{ report.pathogenicity.disease | default_if_none:""}}</td>
            <td>{{ report.pathogenicity.gene | default_if_none:""}}</td>
            <td>{{ report.pathogenicity.variant | default_if_none:""}}</td>
            <td>{{ report.uploaded_at | date:"Y-m-d H:i:s" }}</td>
            <td class="operation-div">
              <button name="update_btn" class="btn btn-sm btn-warning mb-1">修改</button>
              <button name="delete_btn" class="btn btn-sm btn-danger">删除</button>
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <nav aria-label="Page navigation" class="float-right">
      <ul class="pagination">
        {% for page in paginator.page_range %}
          {% if page == page_obj.number %}
          <li class="page-item active"><a class="page-link" href="?{{search}}page={{ page }}">{{ page }}</a></li>
          {% elif page == 1 %}
          <li class="page-item"><a class="page-link" href="?{{search}}page=1" aria-label="Next" >1</a></li>
          {% elif page == paginator.num_pages %}
          <li class="page-item"><a class="page-link" href="?{{search}}page={{ paginator.num_pages }}" aria-label="Next" >{{ paginator.num_pages }}</a></li>
          {% elif page > page_obj.number|add:'-6' and page < page_obj.number|add:'6' %}
          <li class="page-item"><a class="page-link" href="?{{search}}page={{ page }}">{{ page }}</a></li>
          {% elif page == page_obj.number|add:'-6' %}
            <li class="page-item disabled"><a class="page-link" aria-label="Previous">&laquo;</a></li>
          {% elif page == page_obj.number|add:'6' %}
            <li class="page-item disabled"><a class="page-link" aria-label="Next">&raquo;</a></li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>

    <div class="modal fade" id="updateModal">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <!-- Modal Header -->
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <!-- Modal body -->
          <div class="modal-body">
          </div>
          <!-- Modal footer -->
          <div class="modal-footer">
            <button type="button" class="btn btn-md btn-light"> 提交 </button>
            <button type="button" class="btn btn-md btn-primary" data-dismiss="modal"> 取消 </button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="deleteModal">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <!-- Modal Header -->
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-md btn-light"> 删除 </button>
              <button type="button" class="btn btn-md btn-primary" data-dismiss="modal"> 取消 </button>
            </div>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

report/templates/report/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'report/jquery-3.5.1.js' %}" ></script>
    <script src="{% static 'report/popper.min.js' %}" ></script>
    <script src="{% static 'report/bootstrap-4.5.0-dist/js/bootstrap.min.js' %}" ></script>
    {% block scripts %}{% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'report/bootstrap-4.5.0-dist/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'report/css/common.css' %}" >
    {% block css %}{% endblock %}

    <!-- title -->
    <title>{% block title %}{% endblock %}</title>
  </head>


  <body>
    <!-- Navigation Bar -->
    {% include "report/navbar.html" %}

    <!-- Content -->
    {% block content %}{% endblock %}

  </body>
</html>

report/templates/report/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'report:index' %}">
    <img src="{% static 'report/pic/ipmch-logo.png' %}" width="50" height="50" class="d-inline-block align-center" alt="" loading="lazy">
    <div class="logo-text">
      <div>中国福利会国际和平妇幼保健院</div>
      <div>上海交通大学医学院附属国际和平妇幼保健院</div>
    </div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'report:index' %}">
          <svg viewBox="0 0 16 16" class="bi bi-house-fill" fill="currentColor">
            <path fill-rule="evenodd" d="M8 3.293l6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
          </svg>
          单基因病数据库 <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'report:upload' %}">
          <svg viewBox="0 0 16 16" class="bi bi-cloud-upload-fill" fill="currentColor">
            <path fill-rule="evenodd" d="M8 0a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 4.095 0 5.555 0 7.318 0 9.366 1.708 11 3.781 11H7.5V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11h4.188C14.502 11 16 9.57 16 7.773c0-1.636-1.242-2.969-2.834-3.194C12.923 1.999 10.69 0 8 0zm-.5 14.5V11h1v3.5a.5.5 0 0 1-1 0z"/>
          </svg>
          报告上传
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'report:statistics' %}">
          <svg viewBox="0 0 16 16" class="bi bi-reception-4" fill="currentColor">
            <path d="M0 11.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2zm4-3a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-5zm4-3a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-8zm4-3a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v11a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-11z"/>
          </svg>
          数据统计<span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

report/templates/report/report_create_form.html
{% extends "report/layout.html" %}
{% load static %}
<!-- head -->
{% block title %} 国妇婴单基因病报告数据库-报告上传{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'report/css/upload.css' %}" >
{% endblock %}

<!-- body -->
{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'report:index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">上传报告</li>
  </ol>
</nav>
<div class="container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="family">家系号</label>
      <input type="text" class="form-control" name="family">
    </div>
    <div class="form-group">
      <label for="name">姓名</label>
      <input type="text" class="form-control" name="name">
    </div>
    <div class="form-group">
      <label for="disease">疾病</label>
      <input type="text" class="form-control" name="disease">
    </div>
    <div class="form-group">
      <label for="gene">基因</label>
      <input type="text" class="form-control" name="gene">
    </div>
    <div class="form-group">
      <label for="variant">致病变异</label>
      <input type="text" class="form-control" name="variant">
    </div>
    <div class="form-group">
      <label for="pdf">PDF报告</label>
      <input type="file" class="form-control-file" name="pdf">
    </div>
    <button type="submit" class="btn btn-lg btn-primary">上传</button>
  </form>

  {% if messages %}
    <script>
      {% for msg in messages %}
        alert('{{ msg.message }}');
      {% endfor %}
    </script>
    <div class="alert alert-success" role="alert">
    报告上传成功！
    </div>
  {% endif %}
</div>

{% endblock %}

report/templates/report/statistics.html
{% extends "report/layout.html" %}
{% load static %}
<!-- head -->
{% block title %} 国妇婴单基因病报告数据库-数据统计{% endblock %}
{% block css %}
<script src="{% static 'report/echarts.common.js' %}"></script>
<!-- <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script> -->
{% endblock %}

<!-- body -->
{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'report:index' %}">首页</a></li>
    <li class="breadcrumb-item active" aria-current="page">数据统计</li>
  </ol>
</nav>
<div class="container">
  <div id="charts" class="plot" style="height:1200px; width: 1000px;"></div>
  <script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var statsChart = echarts.init(document.getElementById('charts'));
    statsChart.showLoading();

    $.ajax({
      type: "get",
      url: "{% url 'report:api-echarts' %}",
      dataType: "json",
      success: function (data) {
        var option = {
          tooltip: {},
          color: ['#63b7af', '#ff585d', '#ffb549'],
          grid: [
            {bottom: '70%', left: '20%'},
            {top: '35%', bottom: '35%', left: '20%'},
            {top: '70%', left: '20%'},
          ],
          title: {
            left: 'center',
            text: '单基因病报告统计'
          },
          legend: {
            show: true,
            orient: 'vertical',
            align: 'left',
            top: '0%',
            left: '0%',
          },
          xAxis: [
            {type: 'category', data: data.years, gridIndex: 0},
            {gridIndex: 1},
            {gridIndex: 2},
          ],
          yAxis: [
            {gridIndex: 0},
            {type: 'category', data: data.top_10_diseases, gridIndex: 1},
            {type: 'category', data: data.top_10_genes, gridIndex: 2},
          ],
          series: [
            {
              name: '单基因病报告数目统计',
              type: 'bar',
              barWidth: 50,
              data: data.counts,
              label: {
                show: true,
                position: 'insideTop',
                fontWeight: 'bold',
                fontSize: 16,
              }
            },
            {
              name: '数量前10的疾病',
              type: 'bar',
              data: data.top_10_disease_counts,
              xAxisIndex: 1,
              yAxisIndex: 1,
              label: {
                show: true,
                position: 'insideRight',
                fontWeight: 'bold',
                fontSize: 16,
              }
            },
            {
              name: '数量前10的基因',
              type: 'bar',
              data: data.top_10_gene_counts,
              xAxisIndex: 2,
              yAxisIndex: 2,
              label: {
                show: true,
                position: 'insideRight',
                fontWeight: 'bold',
                fontSize: 16,
              }
            },
          ],
        };
        // 使用刚指定的配置项和数据显示图表。
        statsChart.hideLoading();
        statsChart.setOption(option);
      },
      error: function () {
        alert('Error: ajax 请求出错！')
      }
    });
  </script>
</div>

{% endblock %}

report/templates/report/upload.html
{% extends "report/layout.html" %}
{% load static %}
<!-- head -->
{% block title %} 国妇婴单基因病报告数据库-报告上传{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'report/css/upload.css' %}" >
{% endblock %}

<!-- body -->
{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'report:index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">上传报告</li>
  </ol>
</nav>
<div class="container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" id="msg_input" value="{{ msg }}">
    <div class="form-group">
      <label for="family">家系号</label>
      <input type="text" class="form-control" name="family">
    </div>
    <div class="form-group">
      <label for="name">姓名</label>
      <input type="text" class="form-control" name="name">
    </div>
    <div class="form-group">
      <label for="disease">疾病</label>
      <input type="text" class="form-control" name="disease">
    </div>
    <div class="form-group">
      <label for="gene">基因</label>
      <input type="text" class="form-control" name="gene">
    </div>
    <div class="form-group">
      <label for="variant">致病变异</label>
      <input type="text" class="form-control" name="variant">
    </div>
    <div class="form-group">
      <div class="custom-file">
        <input type="file" class="custom-file-input" id="pdf-upload-btn" name="pdf" accept="application/pdf">
        <label class="custom-file-label" for="pdf-upload-btn">PDF上传</label>
      </div>
    </div>
    <button type="submit" class="btn btn-md btn-primary">提交</button>
  </form>

  <div class="modal fade" id="msgModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body" style="min-height: 100px; padding-top: 20px;"></div>
      </div>
    </div>
  </div>

  <script>
  $(function() {
    // show message
    if($('#msg_input').val().trim() !== '') {
      if(window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
      }
      var msg = $('#msg_input').val().trim();
      msg = '<center><h4>' + msg + '</h4></center>';
      $("#msgModal .modal-body").html(msg);
      $("#msgModal").modal('show');
      setTimeout(function(){
        $('#msg_input').val('');
        $("#msgModal").modal("hide");
      }, 2000);
    }
    // upload file btn
    $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
    // check filed of form
    $('body form').on('submit', function() {
      if($('input[name="family"]').val().trim() == '') {
        $('input[name="family"]').focus();
        return false;
      }
      if($('input[name="pdf"]').val().trim() == '') {
        $('input[name="pdf"]').focus();
        return false;
      }
      $(this).append(
        $('<input>').attr({
          'type': 'hidden', 
          'name': 'check_value'
        }).val('1')
      );
    });
  });
  </script>

  {% if messages %}
    <script>
      {% for msg in messages %}
        alert('{{ msg.message }}');
      {% endfor %}
    </script>
  {% endif %}
</div>

{% endblock %}